CREATE VIEW pet_g3db_tfa105.v_merimg_mer (IMG_ID, MER_ID, BUS_ID, MER_NAME, PIC_NAME, MER_PIC, PRICE, STOCK, MAIN_CATEGORY, SUB_CATEGORY)
AS SELECT i.IMG_ID, i.MER_ID, m.BUS_ID, m.NAME, i.PIC_NAME, i.MER_PIC, m.PRICE, m.STOCK, m.MAIN_CATEGORY, m.SUB_CATEGORY
FROM MER_IMG i join MER m on i.MER_ID = m.MER_ID 